"""empty message

Revision ID: 01_healthz_table
Revises:
Create Date: 2020-10-04 19:41:20.633859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01_healthz_table'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'helloworld',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('saying', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('helloworld')
    # ### end Alembic commands ###``
